SemanticAdversarialRegressor.py \
  --train \
  --device gpu:0 \
  -d \
  -i mni_training.txt \
  -t masks_training.txt \
  -o trained_model_gan/ \
  --generator_model UNet2d_generalized \
      --opt_gen AdamOptimizer \
        --opt_learning_rate_gen 0.0005 \
        --opt_learning_decay_rate_gen 0.95 \
      --num_output_channels_gen 1 \
      --dropout_rate_gen 0.5 \
      --filter_size_gen 3 \
      --num_levels_gen 3 \
      --dilation_rate_gen 1 \
      --num_convs_per_level_gen 3 \
      --num_filters_gen 64 \
      --bridge_mode_gen concat \
      --alpha_GDL_gen 0.0 \
  --discriminator_model CNN2d \
    --opt_dis AdamOptimizer \
        --opt_learning_rate_dis 0.0005 \
        --opt_learning_decay_rate_dis 0.95 \
    --num_output_channels_dis 2 \
    --num_blocks_dis 2 \
    --num_elements_dis 3 \
    --num_filters_dis 64 \
    --kernel_size_dis 3 \
    --pool_size_dis 2 \
    --pool_stride_dis 2 \
    --dense_layers_dis 512 512 \
  -main_loss L2 \
  --GDL_weight 0.0 \
  -adversarial_loss AdversarialLeastSquares \
    --adversarial_loss_weight 1.0 \
  --patch_size 64 64 \
  --num_epochs 10 \
  --epoch_size 6400 \
  --batch_size 64 \
  --augment \
    --flip 0 1 \
