SemanticRegressor.py \
  -d \
  --device gpu:1 \
  -i sampledata/2dbrain_mr_test.txt \
  -o predict/ \
  --smoothing_sigma 0.1 \
  --stride_size 16 16 \
  -model_path trained_model/ \
  -model VariationalAutoEncoder2d \
    --num_output_channels 1 \
    --filter_size 3 \
    --num_levels 3 \
    --num_convs_per_level 2 \
    --num_filters 64 \
    --num_hidden_units 2048 \
  --patch_size 64 64 \
  --batch_size 16 \
