SemanticRegressor.py \
  --train \
  --device gpu:1 \
  -d \
  -i sampledata/2dbrain_mr_train.txt \
  -t sampledata/2dbrain_mr_train.txt \
  -o trained_model/ \
  -loss L2 \
  -model VariationalAutoEncoder2d \
    --num_output_channels 1 \
    --filter_size 3 \
    --num_levels 3 \
    --num_convs_per_level 2 \
    --num_filters 64 \
    --num_hidden_units 2048 \
    --alpha_GDL 1.0 \
    --alpha_KL 1.0 \
  --opt AdamOptimizer \
    --opt_learning_rate 0.0005 \
  --patch_size 64 64 \
  --num_epochs 20 \
  --epoch_size 1600 \
  --batch_size 16 \
  --augment \
    --flip 0 1 \
