SemanticAdversarialRegressor.py \
  --device gpu:0 \
  -d \
  -i mni_testing.txt \
  -o predict_gan/ \
  -model_path trained_model_gan/ \
  --generator_model UNet2d_generalized \
      --num_output_channels_gen 1 \
      --dropout_rate_gen 0.0 \
      --filter_size_gen 3 \
      --num_levels_gen 3 \
      --dilation_rate_gen 1 \
      --num_convs_per_level_gen 3 \
      --num_filters_gen 64 \
      --bridge_mode_gen concat \
      --alpha_GDL_gen 0.0 \
  --patch_size 64 64 \
  --batch_size 64 \
